// Category

export const CATEGORY_SET = 'CATEGORY_SET';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORIES_SET = 'CATEGORIES_SET';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_STATE_CLEAR = 'CATEGORY_STATE_CLEAR';

// Message
export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';

//Manafacturer

export const MANUFACTURER_SET = 'MANUFACTURER_SET';
export const MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE';
export const MANUFACTURERS_SET = 'MANUFACTURERS_SET';
export const MANUFACTURER_APPEND = 'MANUFACTURER_APPEND';
export const MANUFACTURER_DELETE = 'MANUFACTURER_DELETE';
export const MANUFACTURER_STATE_CLEAR = 'MANUFACTURER_STATE_CLEAR';
